#pragma once
#include <vector>
#include <string>

inline std::vector<std::string> NAMES = { // 336 names
    "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda",
    "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
    "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa",
    "Matthew", "Margaret", "Anthony", "Betty", "Mark", "Sandra", "Donald", "Ashley",
    "Steven", "Dorothy", "Paul", "Kimberly", "Andrew", "Emily", "Joshua", "Donna",
    "Kenneth", "Michelle", "Kevin", "Carol", "Brian", "Amanda", "George", "Melissa",
    "Edward", "Deborah", "Ronald", "Stephanie", "Timothy", "Rebecca", "Jason", "Laura",
    "Jeffrey", "Helen", "Ryan", "Sharon", "Jacob", "Cynthia", "Gary", "Kathleen",
    "Nicholas", "Amy", "Eric", "Shirley", "Jonathan", "Angela", "Stephen", "Anna",
    "Larry", "Ruth", "Justin", "Brenda", "Scott", "Pamela", "Brandon", "Nicole",
    "Benjamin", "Katherine", "Samuel", "Samantha", "Gregory", "Christine", "Frank", "Emma",
    "Alexander", "Catherine", "Raymond", "Debra", "Patrick", "Virginia", "Jack", "Rachel",
    "Dennis", "Carolyn", "Jerry", "Janet", "Tyler", "Maria", "Aaron", "Heather",
    "Jose", "Diane", "Adam", "Julie", "Henry", "Joyce", "Nathan", "Victoria",
    "Douglas", "Kelly", "Zachary", "Christina", "Peter", "Lauren", "Kyle", "Joan",
    "Walter", "Evelyn", "Ethan", "Olivia", "Jeremy", "Judith", "Harold", "Megan",
    "Keith", "Cheryl", "Christian", "Martha", "Roger", "Andrea", "Noah", "Frances",
    "Gerald", "Hannah", "Carl", "Jacqueline", "Terry", "Gloria", "Sean", "Ann",
    "Austin", "Teresa", "Arthur", "Kathryn", "Lawrence", "Sara", "Jesse", "Janice",
    "Dylan", "Jean", "Jordan", "Alice", "Bryan", "Madison", "Billy", "Doris",
    "Joe", "Abigail", "Bruce", "Julia", "Gabriel", "Judy", "Logan", "Grace",
    "Albert", "Denise", "Willie", "Amber", "Alan", "Marilyn", "Juan", "Beverly",
    "Wayne", "Danielle", "Elijah", "Theresa", "Randy", "Sophia", "Roy", "Marie",
    "Vincent", "Diana", "Ralph", "Brittany", "Eugene", "Natalie", "Russell", "Isabella",
    "Bobby", "Charlotte", "Mason", "Rose", "Philip", "Alexis", "Louis", "Kayla",
    "Harry", "Lori", "Caleb", "Alexandra", "Johnny", "Gabrielle", "Joel", "Lydia",
    "Jimmy", "Tammy", "Antonio", "Kathy", "Aiden", "Shelly", "Chad", "Stacey",
    "Jesus", "Monica", "Herbert", "Erica", "Frederick", "Sheila", "Ray", "Carrie",
    "Joey", "Juanita", "Victor", "Tonya", "Jared", "Holly", "Seth", "Kristin",
    "Martin", "Loretta", "Shane", "Yvonne", "Cory", "Patty", "Clifford", "Stacy",
    "Mitchell", "Ana", "Tracy", "Renee", "Allan", "Ida", "Dale", "Miriam",
    "Leroy", "Billie", "Dean", "Leah", "Reginald", "Melanie", "Alfred", "Peggy",
    "Shawn", "Tracey", "Cameron", "Maxine", "Franklin", "Jill", "Leon", "Carmen",
    "Rodney", "Lillian", "Marvin", "Yolanda", "Jay", "Connie", "Bradley", "Gail",
    "Oscar", "Valerie", "Derek", "Veronica", "Darrell", "Cindy", "Jerome", "Anita",
    "Randall", "Suzanne", "Leo", "Lynn", "Tommy", "Wanda", "Karl", "Felicia",
    "Edwin", "Kristina", "Marcus", "Crystal", "Micheal", "Vicki", "Stanley", "Michele",
    "Claude", "Becky", "Gordon", "Natasha", "Francisco", "Heidi", "Nelson", "Vivian",
    "Eddie", "Rhonda", "Ted", "Roberta", "Todd", "Melinda", "Rick", "Jaime",
    "Curtis", "Marsha", "Andre", "Annette", "Barry", "Kristen", "Alexander", "Charlene",
    "Mario", "Bobbie", "Lonnie", "Olivia", "Kirk", "Agnes", "Neal", "Bertha",
    "Glen", "Robyn", "Dave", "Cassandra", "Ivan", "Nina", "Hector", "Tina"
};